const Workerdata = [
  {
  fName:"Devendra",
  lName:"Khatumariya",
  mobno:8302571961,
  email:"dev@ger.com",
  password:"dty"
  },
  {
    fName:"Devendra",
    lName:"Khatumariya",
    mobno:8302571961,
    email:"dev@ger.com",
    password:"dty"
  },
  {
    fName:"Devendra",
    lName:"Khatumariya",
    mobno:8302571961,
    email:"dev@ger.com",
    password:"dty"
  },
  {
    fName:"Devendra",
    lName:"Khatumariya",
    mobno:8302571961,
    email:"dev@ger.com",
    password:"dty"
  },
  {
    fName:"Devendra",
    lName:"Khatumariya",
    mobno:8302571961,
    email:"dev@ger.com",
    password:"dty"
  },
  {
    fName:"Devendra",
    lName:"Khatumariya",
    mobno:8302571961,
    email:"dev@ger.com",
    password:"dty"
  }
]; 
export default Workerdata;